### ISSUE TITLE
Dont work :(

### ISSUE THREAD

**Issue by Mateusz57698** [KamilPabin/TimbermanBot#1]
C:\Users\MyPc\Desktop\TimberManCheat>python3 main.py
Traceback (most recent call last):
  File "C:\Users\MyPc\Desktop\TimberManCheat\main.py", line 12, in <module>
    tree = Tree(sct)
  File "C:\Users\MyPc\Desktop\TimberManCheat\src\timberman\Tree.py", line 9, in __init__
    self.__tree = [EmptyLog(), EmptyLog(), Log(screen_handle, 3), Log(screen_handle, 4)]
  File "C:\Users\MyPc\Desktop\TimberManCheat\src\timberman\Log.py", line 23, in __init__
    self.take_screenshot()
  File "C:\Users\MyPc\Desktop\TimberManCheat\src\timberman\Log.py", line 26, in take_screenshot
    self.__left_branch = Branch(self.__screen_handle.grab(self.__left_branch_bounding_box), f"left_{self.__position}")
  File "C:\Users\MyPc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mss\base.py", line 88, in grab
    return self._grab_impl(monitor)
  File "C:\Users\MyPc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mss\windows.py", line 270, in _grab_impl
    self.gdi32.BitBlt(
ctypes.ArgumentError: argument 7: <class 'TypeError'>: wrong type

after using s 
:(

**Comment by KamilPabin** [comment]
Hello @Mateusz57698, Thank you for your report! I reproduced your issue on my local machine and now it should be fixed. The problem was definition of bounding boxes for branches. Due to division in bounding box definition resulting width was floating point number, and binding for windows implementation of screen capture expected an int there. I would appreciate if you could check if everything is working fine now.  
Also I added listener for _q_ key press to stop script execution.

**Comment by Mateusz57698** [comment]
there is still some problem, but now a program of a different nature is spamming all the time outside of the game aaaaaa
and when you enter the game, it doesn't do this a

I checked how I will do it with the keyboard and it cuts the tree normally
chapters I tried full screen -> dont full screen 1440x900

for no reaction :(

**Comment by Mateusz57698** [comment]
I will add that I have several monitors if it has an impact

**Comment by KamilPabin** [comment]
Hi @Mateusz57698 just to clarify few things at first:
The script is spamming _a_ keys because it's job is to mimic player interaction, which covers pressing the keys as well.
In timberman _a_ stays for _left_ and _l_ for _right_, it's alternative for arrow keys.  
The script does not specify which monitor to use, so I assume that it will use primary one, so let's stay in a case with just one monitor only :)  

Now for the order of operations:
1. You can start the script by calling `python main.py`, this will start the program and wait for the _s_ keystroke. **DO NOT** click _s_  just yet,
2. Run the timberman, set it to fullscreen, set resolution to 1440x900,
3. Select your character and start the game,
4. Wait until countdown ends and the tree is not obstructed by any other animations. Those animations could mislead script into thinking there is a branch where in reality there is none,
5. Only when the countdown is over and there is nothing in the way of the tree **PRESS s**. Character should start chopping the tree,
6. If the character dies, press _q_ key. This will stop pressing the _a_'s and _l_'s

**Comment by Mateusz57698** [comment]
unfortunately the script won't execute in the game do you know what could be the reason? call keys everywhere else but not in timbermanVS

**Comment by KamilPabin** [comment]
Apparently there is more overhead with different Operating Systems than I originally anticipated. I changed way how key press events are emitted and verified it on Windows, I hope this time it will work.

**Comment by Mateusz57698** [comment]
now the script runs in the game, but it always crashes into the first tree; /
constantly spam key: a

**Comment by Mateusz57698** [comment]
do you know Polish? out of curiosity?
